//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mario.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarioEntities : DbContext
    {
        public MarioEntities()
            : base("name=MarioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppProjects> AppProjects { get; set; }
        public virtual DbSet<AppProjectsBlackTime> AppProjectsBlackTime { get; set; }
        public virtual DbSet<AppProjectsInMobileDevices> AppProjectsInMobileDevices { get; set; }
        public virtual DbSet<AppProjectsInRole> AppProjectsInRole { get; set; }
        public virtual DbSet<AppProjectsRetention> AppProjectsRetention { get; set; }
        public virtual DbSet<DayReport> DayReport { get; set; }
        public virtual DbSet<MarioPackages> MarioPackages { get; set; }
        public virtual DbSet<MobileDevicesLog> MobileDevicesLog { get; set; }
        public virtual DbSet<OperationMessages> OperationMessages { get; set; }
        public virtual DbSet<OperationSchemes> OperationSchemes { get; set; }
        public virtual DbSet<PhoneNumberSection> PhoneNumberSection { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<SystemLog> SystemLog { get; set; }
        public virtual DbSet<UserInfos> UserInfos { get; set; }
        public virtual DbSet<UserInRole> UserInRole { get; set; }
        public virtual DbSet<MobileDeviceModels> MobileDeviceModels { get; set; }
        public virtual DbSet<MobileDevices> MobileDevices { get; set; }
        public virtual DbSet<VirtualIMEI> VirtualIMEI { get; set; }
    }
}
