//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mario.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileDeviceModels
    {
        public int ID { get; set; }
        public string Brand { get; set; }
        public string Device { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public string OSVersion { get; set; }
        public int Weight { get; set; }
        public int RandomStart { get; set; }
        public int RandomEnd { get; set; }
    }
}
