//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mario.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileDevices
    {
        public int ID { get; set; }
        public string Memo { get; set; }
        public bool InUse { get; set; }
        public Nullable<System.DateTime> LastResponseTime { get; set; }
        public long RealIMEI { get; set; }
        public string RealModel { get; set; }
        public bool NeedReboot { get; set; }
    }
}
