//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mario.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationMessages
    {
        public int ID { get; set; }
        public int OperationSchemesID { get; set; }
        public int Step { get; set; }
        public int XPoint { get; set; }
        public int YPoint { get; set; }
        public int ToXPoint { get; set; }
        public int ToYPoint { get; set; }
        public int PhysicalKey { get; set; }
        public int Interval { get; set; }
        public int Action { get; set; }
        public string CommandScript { get; set; }
        public string Memo { get; set; }
    }
}
